import mongoose from "mongoose";
import { db } from "./db/dbConnect.js";
import { Employee } from "./models/employees.model.js";

const testers = [
  {
    "githubId": "6465608",
    "name": "Furquan Khan",
    "username": "furquankhan",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "22660369",
    "name": "Priyanka Bourunde",
    "username": "PriyankaBorunde",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465588",
    "name": "Meghana Thakkekar",
    "username": "MeghanaThakekar",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "13726617",
    "name": "Mahima Patil",
    "username": "Mahimapatil",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "109220027",
    "name": "Prashant Ghule",
    "username": "pghule82",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "106380597",
    "name": "Yogendra Matkar",
    "username": "YogendraMatkar",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "79090746",
    "name": "Vinayak Suryavanshi",
    "username": "Vinayakvs1994",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105647357",
    "name": "Srushti Sakharkar",
    "username": "Srushti225",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105706651",
    "name": "Pooja Ghope",
    "username": "poojaghope",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105647044",
    "name": "Manali Patil",
    "username": "manali1109",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105477460",
    "name": "Mayur Patil",
    "username": "mayurpa22",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105647924",
    "name": "Varsha Golimmbide",
    "username": "vgolimbade",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105647312",
    "name": "Prachi Bansode",
    "username": "bansodeprachi",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "105647075",
    "name": "Umed Gunjal",
    "username": "ugunjal",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "99163263",
    "name": "Noor Ansari",
    "username": "Noor-1898",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "180923893",
    "name": "Abhishek Ugale",
    "username": "abhishek-ugale12",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "87379623",
    "name": "Abdur Rauf",
    "username": "AbdurRauf-Khan",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137782443",
    "name": "Laxmikant Yadav",
    "username": "Laxmikant-Yadav",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "87377156",
    "name": "Lidiya Dominic",
    "username": "Lidiya0402",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "181352727",
    "name": "Achal Kumar",
    "username": "AchalRevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150783001",
    "name": "Ajitpal Singh",
    "username": "ajitSMalhi",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "118966210",
    "name": "Kunal Wavhule",
    "username": "kunalmindmatrix",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "169251980",
    "name": "Amritpal Singh",
    "username": "amritpal0001",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "112927176",
    "name": "Pratik Bhagit",
    "username": "pratikbhagit",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "112927107",
    "name": "Divyesh Hole",
    "username": "DivyeshHole",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "115165149",
    "name": "Amruta Kamble",
    "username": "AmrutaKamble10",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "115164811",
    "name": "Zaid Kadiri",
    "username": "ZaidKadiri",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "42926529",
    "name": "Tajinder Sharma",
    "username": "tajindersharma",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "92525920",
    "name": "Gurinder Singh",
    "username": "gurinder1497",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "109672524",
    "name": "Md Asif Husain",
    "username": "ashifhusainoo7",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "88433214",
    "name": "Anju Vishwakarma",
    "username": "AnjuRV",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "121864967",
    "name": "Rohit Gupta",
    "username": "rohitrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "40827875",
    "name": "Jot Dhaliwal",
    "username": "jotdhaliwal",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "50979631",
    "name": "Rangala Dilleswar Ra",
    "username": "dilleswarrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "88433216",
    "name": "Tamanna Rana",
    "username": "tamannarevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "91262914",
    "name": "Ashwani Patti",
    "username": "Ashwani-revclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "103936597",
    "name": "Priya Badyal",
    "username": "PriyaBadyal",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "185221571",
    "name": "Ali Imam",
    "username": "AliImam02",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "121862721",
    "name": "Saurab Kumar",
    "username": "saurabrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "71871374",
    "name": "Sunil Kumar",
    "username": "sunil768",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "113579435",
    "name": "Komal Chawla",
    "username": "komalchawlarevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "118245398",
    "name": "Parvesh Sharma",
    "username": "SharmaParvesh",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "58559444",
    "name": "Sumit Kumar Mittal",
    "username": "sumitrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "71872682",
    "name": "Salmaan Ali",
    "username": "SalmaanAli",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "92525805",
    "name": "Rohin Sharma",
    "username": "rohin2sharmarevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "121863662",
    "name": "Kumar Chandan",
    "username": "chandanrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "109676892",
    "name": "Abhineet Kumar",
    "username": "abhineetkumar49",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "126570200",
    "name": "Amit Ahuja",
    "username": "amitahujarev",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "97658581",
    "name": "Shakeb Anwer",
    "username": "shakebanwar",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "207057962",
    "name": "Sanika shinde",
    "username": "sanikashinde628",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "84513539",
    "name": "Pushpendra Pandey",
    "username": "pushpendraPande",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "20436878",
    "name": "Rahul Jogdand",
    "username": "Rahulmaxv",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150653428",
    "name": "Sakshi Phalke",
    "username": "sakshii3006",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137781327",
    "name": "Jay Barot",
    "username": "JayBarot10",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "152146521",
    "name": "Cnigdha Soares",
    "username": "Cnigdha",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150241570",
    "name": "Wasim Khan",
    "username": "WasimKhan01",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6941481",
    "name": "Yogesh Gharat",
    "username": "yogeshgharat",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137781165",
    "name": "Kriti Shetty",
    "username": "KritiShetty",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "148982084",
    "name": "Manoj Sharma",
    "username": "manoj-rev",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150241558",
    "name": "Mohommad Hammad",
    "username": "MohammedHammad01",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "115165743",
    "name": "Mohammed Saeed",
    "username": "SaeedMS22",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465580",
    "name": "Abhishek Saiswani",
    "username": "abhisheksaiswani",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "138590209",
    "name": "Evakangra",
    "username": "Evakangra",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "102157495",
    "name": "Raj",
    "username": "Rajrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "14013971",
    "name": "Vinesh Desham",
    "username": "vineshvinnu",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137782841",
    "name": "Ashutosh Pandey",
    "username": "Ashu-990",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "98084240",
    "name": "Sabharee Raj",
    "username": "sabhareeraj",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "117972166",
    "name": "Chinna Kotti Reddy",
    "username": "ChinnaMaxval",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137781971",
    "name": "Dikshita Kasare",
    "username": "Dikshitakasare0108",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150241912",
    "name": "Tushar Gupta",
    "username": "Tushargupta3012",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "32535526",
    "name": "Sayak Mitra",
    "username": "sayak0006",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6492820",
    "name": "Haresh Kedar",
    "username": "HareshKedar",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "170521971",
    "name": "ShubhangiJadhav",
    "username": "shubhangijadhav1212",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "170304379",
    "name": "Akanksha Sharma",
    "username": "Akanksha2321",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "170502556",
    "name": "Abhijith Nair",
    "username": "AbhijithNa1r",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "170519534",
    "name": "Wasima Shaikh",
    "username": "WasimaShaikh",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "150647726",
    "name": "Saba Shaikh",
    "username": "Saba-Sk",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "181114940",
    "name": "Aniket Kumar",
    "username": "AniketRevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "104075619",
    "name": "Dilpreet Kaur",
    "username": "dilpreetkaurrevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "147129454",
    "name": "Harikumar Reddy",
    "username": "lathareddys",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "151126742",
    "name": "Jaskarn Singh",
    "username": "JaskarnSingh1992",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465628",
    "name": "Ubaid Mohammed",
    "username": "ubaidmohammed",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "137782397",
    "name": "Muwaj Mulla",
    "username": "muwaj-mulla",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "180507438",
    "name": "Payal Thakur",
    "username": "PayalRevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465584",
    "name": "Phillip Kanth",
    "username": "pKanth",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "158447729",
    "name": "Sarbjit Raju",
    "username": "Sarbjit-raju",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465652",
    "name": "Shailesh Tayde",
    "username": "shaileshtayde",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465643",
    "name": "Shiv Mishra",
    "username": "shivmishra",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "170304343",
    "name": "Shubham Tyagi",
    "username": "ShubhamTyagiRevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "181352616",
    "name": "Shubhankar Sharma",
    "username": "ShubhankarRevclerx",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6465635",
    "name": "Vishal Patil",
    "username": "Vish-Patil",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "169248530",
    "name": "Yasin Shaikh",
    "username": "yasinshaikh111",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "208835863",
    "name": "Wasi Mohammad",
    "username": "MohddWasi2",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "207058071",
    "name": "Neha Sawant",
    "username": "NehaSawant2306",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": null,
    "contactNumber": null
  },
  {
    "githubId": "6553864",
    "name": "Vardharaj Kawde",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "vardharaj.kawde@rebackoffice.com",
    "contactNumber": null
  },
  {
    "githubId": "6639166",
    "name": "Rohit Haridas",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "rharidas@vectre.net",
    "contactNumber": null
  },
  {
    "githubId": "13694943",
    "name": "Vara Prasad",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "vara.prasad@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "27962160",
    "name": "Amitabh Talukdar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "amitabh.talukdar@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "42613052",
    "name": "Dubbaka Nagarani",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "dubbaka.nagarani@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "45587887",
    "name": "Vidya Bade",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "Vidya.Bade@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "50917627",
    "name": "Lovish Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "lovish@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "54528766",
    "name": "Roma Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "roma@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "54529079",
    "name": "Manjiri Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "manjiri@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "69450747",
    "name": "Parveen Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "parveen@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "90826779",
    "name": "Aditi Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "aditi.thakur@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "97150054",
    "name": "Anuj Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "anuj@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "97150227",
    "name": "Navdeep Singh",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "navdeep.singh@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "102713290",
    "name": "Deeksha Sharma",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "deeksha.sharma@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "103925765",
    "name": "Asher Maxval",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "Asher.Kumar@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "105437575",
    "name": "Anusha Miryala",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "miryala.anusha@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "106654008",
    "name": "Megha Solanke",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "megha.solanke@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "110168689",
    "name": "Priyank Kumar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "priyank.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "110168840",
    "name": "Manish Kumar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "Manish.k@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "110168980",
    "name": "Mitali Thakur",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "mitali.thakur@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "119917459",
    "name": "Imteyaz Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "imteyaz.ahamad@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "123166452",
    "name": "Yash Jain",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "yash.jain@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "125253397",
    "name": "Bhagyashri Wankhade",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "bhagyashri.wankhade@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "125947484",
    "name": "Tarun Mittal",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "tarun.mittal@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "126458596",
    "name": "Prerna Sharma",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "prerna.sharma@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "130961207",
    "name": "Mohit Makhaik",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "mohit.makhaik@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "136305060",
    "name": "Krishnakant Dubey",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "krishnakant.dubey@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "141320879",
    "name": "Dheeraj Sobti",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "dheeraj.sobti@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "143691781",
    "name": "Abhishek Kumar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "abhishek.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "143786706",
    "name": "Eshwar Chavan",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "eshwar.chavan@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "147475567",
    "name": "Kanchan Singh",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "kanchan.singh@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "147475845",
    "name": "Ankit Kumar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "ankit.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "152860609",
    "name": "Sahil Thakur",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "sahil.thakur@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "163122977",
    "name": "Natasha Kapoor",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "natasha.kapoor@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "164486103",
    "name": "Pooja Upreti",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "pooja.upreti@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "167079321",
    "name": "Tarun Jamwal",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "tarun.jamwal@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "175302554",
    "name": "Hritikesh Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "hritikesh.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "178136025",
    "name": "Nishtha Aneja",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "nishtha.aneja@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "178136056",
    "name": "Jasdeep Kaur",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "jasdeep.kaur@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "178142274",
    "name": "Gudia Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "gudia@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "180617195",
    "name": "Sukreeti Sharma",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "sukreeti.sharma@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "182089090",
    "name": "Atul Sharma",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "atul.sharma@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "182471708",
    "name": "Nikhil Sidana",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "nikhil.sidana@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "184734281",
    "name": "Pankaj Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "pankaj@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "187247969",
    "name": "Anandit Sood",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "anandit.sood@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "187263927",
    "name": "Akash Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "akash.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "187360307",
    "name": "Amit Kumar",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "amit.kumar@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "191082149",
    "name": "Meenakshi Revclerx",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "meenakshi@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "191978509",
    "name": "Nikhil Rai",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "nikhil.rai@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "192886068",
    "name": "Abhay Gaikwad",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "abhay.gaikwad@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "192942211",
    "name": "Amandeep Kaur",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "amandeep.kaur@revclerx.com",
    "contactNumber": null
  },
  {
    "githubId": "193463800",
    "name": "Viraj Madhavi",
    "username": null,
    "role": "tester",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "viraj.madhavi@maxval.net",
    "contactNumber": null
  },
  {
    "githubId": "157595414",
    "name": "Venkat Phaneendra Nittala",
    "username": "phani554",
    "role": "developer",
    "reportsTo": null,
    "birthDate": null,
    "joiningDate": null,
    "email": "2023.venkat.nittala@ves.ac.in",
    "contactNumber": null
  }
]

try {
    await db.DBconnect('mongodb://localhost:27017/github-dashboard');
    const connection = mongoose.connection;
    // const cleanDevelopers = testers.map(dev => ({
    //     ...dev,
    //     githubId: dev.githubid
        
    // }));
      
    await Employee.insertMany(testers);
    await mongoose.disconnect();
} catch (error) {
    console.error("Error :", error);
}
